version: '3'
services:
  backend:
    build: ./
    ports:
      - 5000:5000
    networks:
      - mynetwork

  webserver:
    build: ./nginx
    ports:
      - 80:80
    networks:
      - mynetwork

networks:
  mynetwork:
