version: '3.8'
services:
  backend:
    build: ./
    image: ${DOCKER_USER}/personalprojects:v1.01-backend
    environment:
      - MONGO_URI=${MONGO_URI}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}

  webserver:
    build: ./nginx
    image: ${DOCKER_USER}/personalprojects:v1.01-webserver
    ports:
      - 80:80
