version: '3.8'
services:
  backend:
    build: ./
    image: ${DOCKER_USER}/personalprojects:v1.02-backend
    environment:
      - MONGO_URI=${MONGO_URI}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}

  webserver:
    build: ./nginx
    image: ${DOCKER_USER}/personalprojects:v1.02-webserver
    ports:
      - 80:80
      - 443:443
    volumes:
      - certbot:/var/www/certbot/
      - sslkeys:/etc/letsencrypt/

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot:/var/www/certbot/
      - sslkeys:/etc/letsencrypt/

volumes:
  certbot:
  sslkeys:
