name: Server Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      KEY: ${{secrets.EC2_KEY}}
      SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      S3_KEY: ${{ secrets.S3_KEY }}
      S3_SECRET: ${{ secrets.S3_SECRET }}
      PORT: ${{ vars.PORT }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
    steps:
        - uses: actions/checkout@v3
        
        - name: configure ssh
          run: |
            mkdir -p ~/.ssh/
            cd ~/.ssh
            echo "$KEY" > privateKey.pem && chmod 0400 privateKey.pem
            echo "$SSH_CONFIG" > config

        - name: create docker context
          run: docker context create remote --docker "host=ssh://remote"
          
        - name: deploy backend
          run: docker-compose --context remote up -d --build
          
