name: Server Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      KEY: ${{secrets.EC2_KEY}}
      SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
    steps:
        - uses: actions/checkout@v3

        - name: configure ssh
          run: |
          cd ~/.ssh
          echo "$KEY" > privateKey.pem && chmod 0400 privateKey.pem
          echo "$SSH_CONFIG" > config

        - name: create docker context
          run: docker context create remote ‐‐docker “host=ssh://remote”
        
        - name: deploy backend
          run: docker-compose --context remote up -d
          
